# Generated by Django 4.1.7 on 2023-05-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='itens',
            field=models.ManyToManyField(blank=True, null=True, to='carrinho.itemcarrinho'),
        ),
    ]
