# Generated by Django 4.1.7 on 2023-05-10 01:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrinho', '0002_alter_carrinho_itens'),
        ('clientes', '0004_alter_cliente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('endereco', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('referencia', models.CharField(blank=True, max_length=40, null=True)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('valor_total', models.FloatField(verbose_name=models.DecimalField(decimal_places=2, max_digits=10))),
                ('data_compra', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('itens', models.ManyToManyField(blank=True, null=True, to='carrinho.itemcarrinho')),
            ],
        ),
    ]
