# Generated by Django 4.1.7 on 2023-07-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_alter_carrinho_itens'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(blank=True, to='carrinho.itemcarrinho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
