# Generated by Django 4.1.7 on 2023-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_itens_alter_pedido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('em_preparo', 'Em Preparo'), ('saiu_para_entrega', 'Saiu Para Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=17),
        ),
    ]
