# Generated by Django 4.1.7 on 2023-08-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_itens_alter_pedido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_de_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='troco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
