# Generated by Django 4.1.7 on 2023-09-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_metodo_de_pagamento_pedido_troco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('em_preparo', 'Em Preparo'), ('saiu_para_entrega', 'Saiu Para Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=17),
        ),
    ]
