# Generated by Django 4.1.7 on 2023-10-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_borda_descricao'),
        ('pedidos', '0004_alter_itempedido_pedido_alter_pedido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='borda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.borda'),
        ),
    ]
