# Generated by Django 4.1.7 on 2023-09-01 23:30

import cpf_field.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não informado')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('endereco', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('referencia', models.CharField(blank=True, max_length=40, null=True)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('SP', 'São Paulo'), ('NI', 'Não informado')], max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=14, validators=[django.core.validators.MinLengthValidator(14)])),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)])),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
    ]
