# Generated by Django 4.1.7 on 2023-09-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
