# Generated by Django 4.1.7 on 2023-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_alter_carrinho_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='itens',
            field=models.ManyToManyField(blank=True, to='carrinho.itemcarrinho'),
        ),
    ]
