# Generated by Django 4.1.7 on 2023-09-11 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMeioAMeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produto1', to='produtos.produto')),
                ('produto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produto2', to='produtos.produto')),
            ],
        ),
    ]
