# Generated by Django 4.1.7 on 2023-09-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtomeioameio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoBorda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_extra', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
