# Generated by Django 4.1.7 on 2023-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_borda_delete_produtoborda_produto_borda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borda',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
