# Generated by Django 4.1.7 on 2023-11-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_borda_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='borda',
        ),
    ]
